version: '3.4'

services:
  mongo:
    image: mongotest:dev
    container_name: mongo
    ports:
      - '27017:27017'
    build:
      context: .
      dockerfile: Dockerfile
    # volumes: 
    #   - '/data/configdb:/data/configdb'
    #   - '/data/db:/data/db'
  # mongo-express:
  #   image: mongo-express:0.49.0
  #   container_name: mongo_express
  #   depends_on:
  #     - 'mongotest:dev'
  #   ports:
  #     - '5050:8081'
  #   environment:
  #     - 'ME_CONFIG_OPTIONS_EDITORTHEME=ambiance'
